export const entries = [
  {
    id: 1,
    out: true,
    category: "Food",
    subCategory: "Essential",
    date: "2023-09-24",
    value: 30.5,
    note: "Tesco",
  },
  {
    id: 2,
    out: false,
    category: "Gift",
    subCategory: "",
    date: "2023-09-25",
    value: 100,
    note: "",
  },
  {
    id: 3,
    out: true,
    category: "Bills",
    subCategory: "Electric",
    date: "2023-09-26",
    value: 60.2,
    note: "",
  },
  {
    id: 4,
    out: true,
    category: "Food",
    subCategory: "Delivery",
    date: "2023-09-27",
    value: 15.97,
    note: "KFC",
  },
  {
    id: 5,
    out: true,
    category: "Bills",
    subCategory: "Water",
    date: "2023-08-21",
    value: 20,
    note: "",
  }
];